# Generated by Django 5.0.3 on 2024-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
