# Generated by Django 5.0.3 on 2024-03-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_comment_alter_staff_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="workrecord",
            constraint=models.UniqueConstraint(
                fields=("staff", "date"), name="unique_work_record"
            ),
        ),
    ]
